# Simple Matrix Operations with NumPy

## 1. Import NumPy

In [1]:
import numpy as np

## 2. Create Two Matrices

Here we create two simple 2 × 2 matrices.

In [2]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


## 3. Matrix Addition

`+` adds two matrices element by element.

In [12]:
print("A + B:")
print(A + B)

A + B:
[[ 6  8]
 [10 12]]


## 4. Matrix Subtraction

`-` subtracts two matrices element by element.

In [13]:
print("A - B:")
print(A - B)

A - B:
[[-4 -4]
 [-4 -4]]


## 5. Element-wise Multiplication

`*` multiplies matching elements.

This is **not** standard matrix multiplication.

In [14]:
print("A * B:")
print(A * B)

A * B:
[[ 5 12]
 [21 32]]


## 6. Matrix Multiplication

`@` performs real matrix multiplication.

You can also use `np.dot(A, B)`.

In [15]:
print("A @ B:")
print(A @ B)

print("\nnp.dot(A, B):")
print(np.dot(A, B))

A @ B:
[[19 22]
 [43 50]]

np.dot(A, B):
[[19 22]
 [43 50]]


## 7. Division

`/` divides matching elements.

This is element-wise division.

In [16]:
print("B / A:")
print(B / A)

B / A:
[[5.         3.        ]
 [2.33333333 2.        ]]


## 8. Transpose

`.T` changes rows into columns.

In [17]:
print("A Transpose:")
print(A.T)

A Transpose:
[[1 3]
 [2 4]]


## 9. Identity Matrix

`np.eye(size)` creates an identity matrix.

In [18]:
I = np.eye(2)

print("Identity Matrix:")
print(I)

Identity Matrix:
[[1. 0.]
 [0. 1.]]


## 10. Check Matrix Shape

`.shape` tells the size of the matrix.

In [19]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

Shape of A: (2, 2)
Shape of B: (2, 2)


## 11. Simple User Input Version

This version lets the user enter two matrices manually.

Only normal numbers are used. No complex numbers.

In [23]:
def input_matrix(name, rows, cols):
    matrix = []
    print(f"Enter values for Matrix {name}:")
    
    for i in range(rows):
        row = input(f"Row {i + 1}: ").split()
        row = [float(x) for x in row]
        matrix.append(row)
    
    return np.array(matrix)

In [25]:
# Uncomment this section if you want manual input.

rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

user_A = input_matrix("A", rows, cols)
user_B = input_matrix("B", rows, cols)

print("\nUser Matrix A:")
print(user_A)

print("\nUser Matrix B:")
print(user_B)

print("\nA + B:")
print(user_A + user_B)

print("\nA - B:")
print(user_A - user_B)

print("\nA * B:")
print(user_A * user_B)

if cols == rows:
    print("\nA @ B:")
    print(user_A @ user_B)
else:
    print("\nMatrix multiplication A @ B is not valid for these dimensions.")

Enter number of rows:  2
Enter number of columns:  2


Enter values for Matrix A:


Row 1:  1
Row 2:  2


Enter values for Matrix B:


Row 1:  3
Row 2:  4



User Matrix A:
[[1.]
 [2.]]

User Matrix B:
[[3.]
 [4.]]

A + B:
[[4.]
 [6.]]

A - B:
[[-2.]
 [-2.]]

A * B:
[[3.]
 [8.]]

A @ B:


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)